### ISSUE TITLE
Keynote speaker information translate

### ISSUE THREAD

**Issue by WillemJiang** [apache/apachecon-acasia#180]
We need to translate the keynote speaker information into Chinese. 
https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2000.zh.md
https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2001.zh.md
https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2003.zh.md
https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2004.zh.md

**Comment by jnjt115** [comment]
https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2003.zh.md
演讲主题：《促进社区成长的实践路径》
内容介绍：构建活跃的贡献者社区对于任何一个开源项目而言，可能都是最困难的工作，但是如果没有这样一个活跃的社区，项目将很难长期发展下去。虽然社区成长与其说是科学，不如说是艺术，但仍有一些实践操作可以帮助社区让人们更有可能想要加入进来。本次演讲，Rich将会把自己20多年的社区运营经验分享给大家。
演讲嘉宾：
Rich Bowen，Apache软件基金会（ASF）会员，七次担任基金会董事，他是ASF的会议策划副总裁（VP Conferences），也是Community Development PMC的成员，还是AWS的开源布道者。

注：表格中的演讲嘉宾与正文中的不一致

**Comment by jnjt115** [comment]
> We need to translate the keynote speaker information into Chinese. https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2000.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2001.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2003.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2004.zh.md

https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2003.zh.md
演讲主题：《促进社区成长的实践路径》
内容介绍：构建活跃的贡献者社区对于任何一个开源项目而言，可能都是最困难的工作，但是如果没有这样一个活跃的社区，项目将很难长期发展下去。虽然社区成长与其说是科学，不如说是艺术，但仍有一些实践操作可以帮助社区让人们更有可能想要加入进来。本次演讲，Rich将会把自己20多年的社区运营经验分享给大家。
演讲嘉宾：
Rich Bowen，Apache软件基金会（ASF）会员，七次担任基金会董事，他是ASF的会议策划副总裁（VP Conferences），也是Community Development PMC的成员，还是AWS的开源布道者。

注：表格中的演讲嘉宾与正文中的不一致

**Comment by Christine0416** [comment]
> We need to translate the keynote speaker information into Chinese. https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2000.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2001.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2003.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2004.zh.md

演讲主题：品牌管理 - 概述
内容介绍：
本次演讲主要面向 Apache 项目的提交者。首先会介绍品牌与商标的概念，阐述它们与社区项目的关系以及它们如何助力社区项目的健康发展。主要内容涵盖品牌管理团队为项目提供的各项服务，探究这些每年耗资 ASF（Apache软件基金组织）6万至8万美元的服务的典型成本项。

商标注册，将着眼于讨论注册项目商标的收益、注册过程以及如何选择申请注册的国家。同时，还将关注将现有的商标转移到ASF所能带来的收益。

商标使用，将阐释我们如何授权使用商标，以及我们通常允许做的和不允许做的。这可能对希望基于 Apache 项目构建产品的公司有所助益，因为他们可以确保合理地使用我们的商标。

管理潜在侵权事件，将描述在解决项目商标潜在侵权案件时，我们应该做的和不应该做的关键事项，使项目得以最大程度地避免纷争，妥善解决问题。

演讲嘉宾：Mark Thomas
Mark 自 2003 年 11 月以来一直是 Apache Tomcat 项目的提交者。他最初是在空闲时间从事 Tomcat 开发工作，但自 2008 年 8 月以来，他受雇于 SpringSource（现归属于VMware旗下）全职从事 Apache Tomcat项目的研发。Mark的大部分时间都投入到了 Tomcat研发，但与此同时，他也参与开发基于Apache Tomcat的 tc Server、VMware 的 Servlet & JSP 容器项目。
Mark 是 Apache Tomcat 10.0 和 10.1 的版本经理，他尝试几乎每个月就发布一个新版本。目前，他正全身心投入到支持 Jakarta EE 10 的 Tomcat 10.1 的研发工作。同时，他也是 Eclipse Servlet、服务器页面、表达式语言和 WebSocket 的提交者。

在 ASF 中，Mark还有另一个角色 — ASF 安全与基础架构团队的成员，同时，他也是Commons PMC的成员，从事 Commons Pool 和 DBCP的开发。

Mark 是ASF的成员，于2016年至2019年担任董事。自2018年2月起，他开始以品牌管理副总裁的身份继续工作。

**Comment by Erickkkkk** [comment]
https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2000.zh.md

演讲主题：《OpenChain 项目介绍》

内容介绍：
开源软件、供应链和合规性是现代贸易的核心。许可证合规性已经与安全合规性一起成为贸易的中心要素。 在本次主题演讲中，ISO开源许可合规标准的总经理 Shane Coughlan 将讲解他的社区和其他相邻社区组织正在做的事情，从而使得一切都变得更快速、更安全，并且更高效。

演讲嘉宾：
Shane Coughlan 是通信、安全和业务发展方面的专家。他的职业成就包括通过 OpenChain 项目建立了世界上最大的开源治理社区，并带领许可团队将“开放创新网络”晋升为历史上最大的专利互不侵略社区，同时建立了第一个全球开源法律专家网络。他创始了专注于开源软件的第一本法律期刊和第一法律书籍。他目前领导 OpenChain 项目，并担任 World Mobile 的顾问，同时还是 OpenForum Europe 的大会成员。

**Comment by Erickkkkk** [comment]
> We need to translate the keynote speaker information into Chinese. https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2000.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2001.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2003.zh.md https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2004.zh.md

https://github.com/apache/apachecon-acasia/blob/master/content/sessions/keynote-2000.zh.md

演讲主题：《OpenChain 项目介绍》

内容介绍：
开源软件、供应链和合规性是现代贸易的核心。许可证合规性已经与安全合规性一起成为贸易的中心要素。 在本次主题演讲中，ISO开源许可合规标准的总经理 Shane Coughlan 将讲解他的社区和其他相邻社区组织正在做的事情，从而使得一切都变得更快速、更安全，并且更高效。

演讲嘉宾：
Shane Coughlan 是通信、安全和业务发展方面的专家。他的职业成就包括通过 OpenChain 项目建立了世界上最大的开源治理社区，并带领许可团队将“开放创新网络”晋升为历史上最大的专利互不侵略社区，同时建立了第一个全球开源法律专家网络。他创始了专注于开源软件的第一本法律期刊和第一法律书籍。他目前领导 OpenChain 项目，并担任 World Mobile 的顾问，同时还是 OpenForum Europe 的大会成员。

**Comment by WillemJiang** [comment]
Merged the PRs.
